version: "3.1"

services:
  app:
    container_name: voting_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - "27018:27017"
    command: mongod